name: Fetch Doodles Data

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day
  workflow_dispatch: # Manual trigger

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js version compatible with your code

      - name: Install Dependencies
        run: npm install axios

      - name: Run Data Fetch Script
        run: node index.js
