name: Fetch Doodles Data

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day
  workflow_dispatch: # Manual trigger

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install axios

      - name: Set up git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch data and commit changes
        run: node index.js

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto-fetch doodles data [skip ci]"
          git push
